language: cpp

os: windows
group: dev

branches:
  only:
  - master

env:
  - MSBUILD_PATH: "'/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin'"

before_install:
  - export PATH=$MSBUILD_PATH:${PATH}
  
install:
  - powershell Install-WindowsFeature Net-Framework-Core;
  - cinst -y --no-progress wixtoolset;
  
script:
  - cmd.exe /C "dir"
  - cmd.exe /C "MSBuild.exe TestApp/TestApp.sln"

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "TestApp/TestInstaller/bin/*/*.msi"
    skip_cleanup: true
    on:
      branch: master
